apiVersion: v1
kind: Service
metadata:
  name: {{ include "power-position-service.fullname" . }}
  labels:
    {{- include "power-position-service.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "power-position-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: dummy
      port: 80
      targetPort: 80
